### ISSUE TITLE
Ability to set minimum and maximum date range

### ISSUE THREAD

**Issue by jasonmitchell** [jasonmitchell/WinRT-XAML-DatePicker#3]

**Comment by gustavocalheiros** [comment]
Hi,

If we navigate in years field using pageDown/Up, until the year 0, the app crashes. Think we can put just one attribute that limits at least the year range.

**Comment by jasonmitchell** [comment]
Oh dear.  Should definitely put in something to stop you going below 0 and above 9999 since that's the max DateTime supports
