### ISSUE TITLE
are you able to export an event to notify when the SelectedDate changes?

### ISSUE THREAD

**Issue by harrykimpel** [jasonmitchell/WinRT-XAML-DatePicker#6]

**Comment by jasonmitchell** [comment]
I was thinking this would be useful when I was doing a bit of work on it last night.  I'll put it on my to do list.

**Comment by harrykimpel** [comment]
Thanks! Other than that, this is a useful and great control!

Regards,

Harry

Gesendet von Windows-Mail

Von: Jason Mitchell
Gesendet: ‎Mittwoch‎, ‎3‎. ‎April‎ ‎2013 ‎10‎:‎17
An: jasonmitchell/WinRT-XAML-DatePicker
Cc: harrykimpel

I was thinking this would be useful when I was doing a bit of work on it last night. I'll put it on my to do list.

**Comment by TheXby** [comment]
What status of this issue? I need to refresh page after date changes, but now it's impossible.

**Comment by jasonmitchell** [comment]
No updates yet.  I will try make time to look at this later today for you.

**Comment by jasonmitchell** [comment]
Added this change.  Now available on NuGet: https://nuget.org/packages/WinRT-DatePicker/
