### ISSUE TITLE
Month name gets overlaped when navigating using Home/End keys

### ISSUE THREAD

**Issue by gustavocalheiros** [jasonmitchell/WinRT-XAML-DatePicker#8]
1- click on the month component.
2- Press "end"
3- Press "home"

The string "september" overlaps the string "december"

**Comment by jasonmitchell** [comment]
I've been able to reproduce this.  However I also recreated it in an empty app with just a combo box with month names in it which is interesting.  I will do a little bit of searching and see if there are any suggested work arounds.

**Comment by gustavocalheiros** [comment]
good! Let me know if find out something.
