### ISSUE TITLE
AssemblyCulture is set to en-GB, causing a 1607 compiler warning

### ISSUE THREAD

**Issue by mafuba** [jasonmitchell/WinRT-XAML-DatePicker#9]
When referenced by an assembly with no culture or different culture, the compiler generates a 1607 warning: `The assembly in file "...\packages\WinRT-DatePicker.1.0.1\lib\netcore45\WinRTDatePicker.dll" has an assembly culture, indicating it is a satellite assembly for culture "en-GB".  But satellite assembly simple names must end in ".resources", while this one's simple name is "WinRTDatePicker".  This is either a main assembly with the culture incorrectly set, or a satellite assembly with an incorrect simple name.`

**Comment by jasonmitchell** [comment]
Thanks.  I've updated the NuGet package
